# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 60s
  issues-exit-code: 1
  tests: true
  timeout: 10m
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - frontend
  skip-files:
    - \.pb\.go$
    - \.pb\.gw\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 500
    # Tab width in spaces.
    # Default: 1
    tab-width: 2
  misspell:
    locale: US
  paralleltest:
    ignore-missing: false

linters:
  disable-all: true
  enable:
    # todo add dupl
    - misspell
    - unused
    - goimports
    - goconst
    - revive
    - errcheck
    - noctx
    - nilerr
    - paralleltest
    - lll
