# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 60s
  issues-exit-code: 1
  tests: true
  timeout: 10m
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - frontend
  skip-files:
    - \.pb\.go$
    - \.pb\.gw\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - goimports
    - exportloopref
